//About Hero Area Constant
export const ABOUT_CONTENT_REQUEST = "ABOUT_CONTENT_REQUEST";
export const ABOUT_CONTENT_SUCCESS = "ABOUT_CONTENT_SUCCESS";
export const ABOUT_CONTENT_FAIL = "ABOUT_CONTENT_FAIL";

export const SINGLE_ABOUT_CONTENT_REQUEST = "SINGLE_ABOUT_CONTENT_REQUEST";
export const SINGLE_ABOUT_CONTENT_SUCCESS = "SINGLE_ABOUT_CONTENT_SUCCESS";
export const SINGLE_ABOUT_CONTENT_FAIL = "SINGLE_ABOUT_CONTENT_FAIL";

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL";
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
