export const CONTACT_CONTENT_REQUEST = "CONTACT_CONTENT_REQUEST";
export const CONTACT_CONTENT_SUCCESS = "CONTACT_CONTENT_SUCCESS";
export const CONTACT_CONTENT_FAIL = "CONTACT_CONTENT_FAIL";

export const SINGLE_CONTACT_REQUEST = "SINGLE_CONTACT_REQUEST";
export const SINGLE_CONTACT_SUCCESS = "SINGLE_CONTACT_SUCCESS";
export const SINGLE_CONTACT_FAIL = "SINGLE_CONTACT_FAIL";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";
export const UPDATE_CONTACT_RESET = "UPDATE_CONTACT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";