export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";

export const COURSE_CONTENT_REQUEST = "COURSE_CONTENT_REQUEST";
export const COURSE_CONTENT_SUCCESS = "ABOUT_CONTENT_SUCCESS";
export const COURSE_CONTENT_FAIL = "COURSE_CONTENT_FAIL";

export const SINGLE_COURSE_CONTENT_REQUEST = "SINGLE_COURSE_CONTENT_REQUEST";
export const SINGLE_COURSE_CONTENT_SUCCESS = "SINGLE_COURSE_CONTENT_SUCCESS";
export const SINGLE_COURSE_CONTENT_FAIL = "SINGLE_COURSE_CONTENT_FAIL";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";
export const UPDATE_COURSE_RESET = "UPDATE_COURSE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";