export const FAQ_CONTENT_REQUEST = "FAQ_CONTENT_REQUEST";
export const FAQ_CONTENT_SUCCESS = "FAQ_CONTENT_SUCCESS";
export const FAQ_CONTENT_FAIL = "FAQ_CONTENT_FAIL";

export const SINGLE_FAQ_REQUEST = "SINGLE_FAQ_REQUEST";
export const SINGLE_FAQ_SUCCESS = "SINGLE_FAQ_SUCCESS";
export const SINGLE_FAQ_FAIL = "SINGLE_FAQ_FAIL";

export const UPDATE_FAQ_REQUEST = "UPDATE_FAQ_REQUEST";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_FAIL = "UPDATE_FAQ_FAIL";
export const UPDATE_FAQ_RESET = "UPDATE_FAQ_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";