
export const FIVEIMG_CREATE_REQUEST = "FIVEIMG_CREATE_REQUEST";
export const FIVEIMG_CREATE_SUCCESS = "FIVEIMG_CREATE_SUCCESS";
export const FIVEIMG_CREATE_FAIL = "FIVEIMG_CREATE_FAIL";
export const FIVEIMG_CREATE_RESET = "FIVEIMG_CREATE_RESET";

export const FIVEIMG_CONTENT_REQUEST = "FIVEIMG_CONTENT_REQUEST";
export const FIVEIMG_CONTENT_SUCCESS = "FIVEIMG_CONTENT_SUCCESS";
export const FIVEIMG_CONTENT_FAIL = "FIVEIMG_CONTENT_FAIL";

export const SINGLE_FIVEIMG_REQUEST = "SINGLE_FIVEIMG_REQUEST";
export const SINGLE_FIVEIMG_SUCCESS = "SINGLE_FIVEIMG_SUCCESS";
export const SINGLE_FIVEIMG_FAIL = "SINGLE_FIVEIMG_FAIL";

export const UPDATE_FIVEIMG_REQUEST = "UPDATE_FIVEIMG_REQUEST";
export const UPDATE_FIVEIMG_SUCCESS = "UPDATE_FIVEIMG_SUCCESS";
export const UPDATE_FIVEIMG_FAIL = "UPDATE_FIVEIMG_FAIL";
export const UPDATE_FIVEIMG_RESET = "UPDATE_FIVEIMG_RESET";

export const DELETE_FIVEIMG_REQUEST = "DELETE_FIVEIMG_REQUEST";
export const DELETE_FIVEIMG_SUCCESS = "DELETE_FIVEIMG_SUCCESS";
export const DELETE_FIVEIMG_FAIL = "DELETE_FIVEIMG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";