//Hero Area Constant
export const ALL_CONTENT_REQUEST = "ALL_CONTENT_REQUEST";
export const ALL_CONTENT_SUCCESS = "ALL_CONTENT_SUCCESS";
export const ALL_CONTENT_FAIL = "ALL_CONTENT_FAIL";

export const CREATE_HERO_REQUEST = "CREATE_HERO_REQUEST";
export const CREATE_HERO_SUCCESS = "CREATE_HERO_SUCCESS";
export const CREATE_HERO_FAIL = "CREATE_HERO_FAIL";
export const CREATE_HERO_RESET = "CREATE_HERO_RESET";

export const UPDATE_HEROAREA_REQUEST = "UPDATE_HEROAREA_REQUEST";
export const UPDATE_HEROAREA_SUCCESS = "UPDATE_HEROAREA_SUCCESS";
export const UPDATE_HEROAREA_FAIL = "UPDATE_HEROAREA_FAIL";
export const UPDATE_HEROAREA_RESET = "UPDATE_HEROAREA_RESET";

export const HEROAREA_CONTENT_REQUEST = "HEROAREA_CONTENT_REQUEST";
export const HEROAREA_CONTENT_SUCCESS = "HEROAREA_CONTENT_SUCCESS";
export const HEROAREA_CONTENT_FAIL = "HEROAREA_CONTENT_FAIL";

//Feature Area Constant
export const FEATURE_CONTENT_REQUEST = "FEATURE_CONTENT_REQUEST";
export const FEATURE_CONTENT_SUCCESS = "FEATURE_CONTENT_SUCCESS";
export const FEATURE_CONTENT_FAIL = "FEATURE_CONTENT_FAIL";

export const SINGLE_FEATURE_REQUEST = "SINGLE_FEATURE_REQUEST";
export const SINGLE_FEATURE_SUCCESS = "SINGLE_FEATURE_SUCCESS";
export const SINGLE_FEATURE_FAIL = "SINGLE_FEATURE_FAIL";

export const UPDATE_FEATURE_REQUEST = "UPDATE_FEATURE_REQUEST";
export const UPDATE_FEATURE_SUCCESS = "UPDATE_FEATURE_SUCCESS";
export const UPDATE_FEATURE_FAIL = "UPDATE_FEATURE_FAIL";
export const UPDATE_FEATURE_RESET = "UPDATE_FEATURE_RESET";

//Pricing Area Constant
export const PRICING_CONTENT_REQUEST = "PRICING_CONTENT_REQUEST";
export const PRICING_CONTENT_SUCCESS = "PRICING_CONTENT_SUCCESS";
export const PRICING_CONTENT_FAIL = "PRICING_CONTENT_FAIL";

export const SINGLE_PRICING_REQUEST = "SINGLE_PRICING_REQUEST";
export const SINGLE_PRICING_SUCCESS = "SINGLE_PRICING_SUCCESS";
export const SINGLE_PRICING_FAIL = "SINGLE_PRICING_FAIL";

export const UPDATE_PRICING_REQUEST = "UPDATE_PRICING_REQUEST";
export const UPDATE_PRICING_SUCCESS = "UPDATE_PRICING_SUCCESS";
export const UPDATE_PRICING_FAIL = "UPDATE_PRICING_FAIL";
export const UPDATE_PRICING_RESET = "UPDATE_PRICING_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";