export const INDFEES_CONTENT_REQUEST = "INDFEES_CONTENT_REQUEST";
export const INDFEES_CONTENT_SUCCESS = "INDFEES_CONTENT_SUCCESS";
export const INDFEES_CONTENT_FAIL = "INDFEES_CONTENT_FAIL";

export const SINGLE_INDFEES_REQUEST = "SINGLE_INDFEES_REQUEST";
export const SINGLE_INDFEES_SUCCESS = "SINGLE_INDFEES_SUCCESS";
export const SINGLE_INDFEES_FAIL = "SINGLE_INDFEES_FAIL";

export const UPDATE_INDFEES_REQUEST = "UPDATE_INDFEES_REQUEST";
export const UPDATE_INDFEES_SUCCESS = "UPDATE_INDFEES_SUCCESS";
export const UPDATE_INDFEES_FAIL = "UPDATE_INDFEES_FAIL";
export const UPDATE_INDFEES_RESET = "UPDATE_INDFEES_RESET";

export const QUICKTEST_CONTENT_REQUEST = "QUICKTEST_CONTENT_REQUEST";
export const QUICKTEST_CONTENT_SUCCESS = "QUICKTEST_CONTENT_SUCCESS";
export const QUICKTEST_CONTENT_FAIL = "QUICKTEST_CONTENT_FAIL";

export const SINGLE_QUICKTEST_REQUEST = "SINGLE_QUICKTEST_REQUEST";
export const SINGLE_QUICKTEST_SUCCESS = "SINGLE_QUICKTEST_SUCCESS";
export const SINGLE_QUICKTEST_FAIL = "SINGLE_QUICKTEST_FAIL";

export const UPDATE_QUICKTEST_REQUEST = "UPDATE_QUICKTEST_REQUEST";
export const UPDATE_QUICKTEST_SUCCESS = "UPDATE_QUICKTEST_SUCCESS";
export const UPDATE_QUICKTEST_FAIL = "UPDATE_QUICKTEST_FAIL";
export const UPDATE_QUICKTEST_RESET = "UPDATE_QUICKTEST_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";