export const ONCLS_CONTENT_REQUEST = "ONCLS_CONTENT_REQUEST";
export const ONCLS_CONTENT_SUCCESS = "ONCLS_CONTENT_SUCCESS";
export const ONCLS_CONTENT_FAIL = "ONCLS_CONTENT_FAIL";

export const SINGLE_ONCLS_REQUEST = "SINGLE_ONCLS_REQUEST";
export const SINGLE_ONCLS_SUCCESS = "SINGLE_ONCLS_SUCCESS";
export const SINGLE_ONCLS_FAIL = "SINGLE_ONCLS_FAIL";

export const UPDATE_ONCLS_REQUEST = "UPDATE_ONCLS_REQUEST";
export const UPDATE_ONCLS_SUCCESS = "UPDATE_ONCLS_SUCCESS";
export const UPDATE_ONCLS_FAIL = "UPDATE_ONCLS_FAIL";
export const UPDATE_ONCLS_RESET = "UPDATE_ONCLS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";