//Pricing Area Constant
export const PACKAGE_CONTENT_REQUEST = "PACKAGE_CONTENT_REQUEST";
export const PACKAGE_CONTENT_SUCCESS = "PACKAGE_CONTENT_SUCCESS";
export const PACKAGE_CONTENT_FAIL = "PACKAGE_CONTENT_FAIL";

export const SINGLE_PACKAGE_REQUEST = "SINGLE_PACKAGE_REQUEST";
export const SINGLE_PACKAGE_SUCCESS = "SINGLE_PACKAGE_SUCCESS";
export const SINGLE_PACKAGE_FAIL = "SINGLE_PACKAGE_FAIL";

export const UPDATE_PACKAGE_REQUEST = "UPDATE_PACKAGE_REQUEST";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_FAIL = "UPDATE_PACKAGE_FAIL";
export const UPDATE_PACKAGE_RESET = "UPDATE_PACKAGE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";