
export const SIXIMG_CREATE_REQUEST = "SIXIMG_CREATE_REQUEST";
export const SIXIMG_CREATE_SUCCESS = "SIXIMG_CREATE_SUCCESS";
export const SIXIMG_CREATE_FAIL = "SIXIMG_CREATE_FAIL";
export const SIXIMG_CREATE_RESET = "SIXIMG_CREATE_RESET";

export const SIXIMG_CONTENT_REQUEST = "SIXIMG_CONTENT_REQUEST";
export const SIXIMG_CONTENT_SUCCESS = "SIXIMG_CONTENT_SUCCESS";
export const SIXIMG_CONTENT_FAIL = "SIXIMG_CONTENT_FAIL";

export const SINGLE_SIXIMG_REQUEST = "SINGLE_SIXIMG_REQUEST";
export const SINGLE_SIXIMG_SUCCESS = "SINGLE_SIXIMG_SUCCESS";
export const SINGLE_SIXIMG_FAIL = "SINGLE_SIXIMG_FAIL";

export const UPDATE_SIXIMG_REQUEST = "UPDATE_SIXIMG_REQUEST";
export const UPDATE_SIXIMG_SUCCESS = "UPDATE_SIXIMG_SUCCESS";
export const UPDATE_SIXIMG_FAIL = "UPDATE_SIXIMG_FAIL";
export const UPDATE_SIXIMG_RESET = "UPDATE_SIXIMG_RESET";

export const DELETE_SIXIMG_REQUEST = "DELETE_SIXIMG_REQUEST";
export const DELETE_SIXIMG_SUCCESS = "DELETE_SIXIMG_SUCCESS";
export const DELETE_SIXIMG_FAIL = "DELETE_SIXIMG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";